// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uialberto.Northwind.DataAccess;

namespace Uialberto.Northwind.DataAccess.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Uialberto.Northwind.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EmployeeType");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasDiscriminator<byte>("EmployeeType").HasValue((byte)0);

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            FirstName = "Alberto",
                            LastName = "Reyes"
                        },
                        new
                        {
                            EmployeeID = 2,
                            FirstName = "Fernando",
                            LastName = "Baigorria"
                        });
                });

            modelBuilder.Entity("Uialberto.Northwind.Entities.Vendedor", b =>
                {
                    b.HasBaseType("Uialberto.Northwind.Entities.Employee");

                    b.Property<int>("SellingAreaID");

                    b.HasDiscriminator().HasValue((byte)1);

                    b.HasData(
                        new
                        {
                            EmployeeID = 3,
                            FirstName = "Milton",
                            LastName = "Lazo",
                            SellingAreaID = 1
                        },
                        new
                        {
                            EmployeeID = 4,
                            FirstName = "Wilson",
                            LastName = "Lazo",
                            SellingAreaID = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
